-- -------------------------------------------------------
-- Laravel Bookstore Project Database Initialization Script
-- -------------------------------------------------------
-- Creation Date: 2025
-- Character Set: utf16_unicode_ci
-- Engine: InnoDB
-- -------------------------------------------------------
